# Generated by Django 5.0.6 on 2024-05-23 12:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('town_square', '0002_raceevent_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceevent',
            name='event_image',
            field=cloudinary.models.CloudinaryField(default='event_placeholder', max_length=255, verbose_name='Event image'),
        ),
        migrations.AlterField(
            model_name='raceevent',
            name='event_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
