# Generated by Django 5.0.6 on 2024-05-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('town_square', '0002_raceevent_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceevent',
            name='slug',
            field=models.SlugField(default='def', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raceevent',
            name='event_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
