# Generated by Django 5.0.6 on 2024-05-23 07:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('town_square', '0003_raceevent_slug_alter_raceevent_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceevent',
            name='event_image',
            field=cloudinary.models.CloudinaryField(default='event_placeholder', max_length=255, verbose_name='Event image'),
        ),
    ]
