# Generated by Django 5.0.6 on 2024-05-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('town_square', '0003_alter_raceevent_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceevent',
            name='location',
            field=models.CharField(max_length=32),
        ),
    ]
