# Generated by Django 5.0.6 on 2024-05-24 14:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('town_square', '0004_alter_raceevent_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceevent',
            name='event_image',
        ),
        migrations.AddField(
            model_name='raceevent',
            name='event_circuit',
            field=cloudinary.models.CloudinaryField(default='event_placeholder', max_length=255, verbose_name='Event circuit'),
        ),
    ]
