# Generated by Django 5.0.6 on 2024-05-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('town_square', '0005_remove_raceevent_event_image_raceevent_event_circuit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raceevent',
            options={'ordering': ['start_date']},
        ),
    ]
