# Generated by Django 5.0.6 on 2024-05-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('town_square', '0006_alter_raceevent_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceevent',
            name='end_date',
        ),
    ]
