# Generated by Django 5.0.6 on 2024-05-23 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('town_square', '0003_alter_raceevent_event_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedRaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_info', models.TextField()),
                ('race', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_details', to='town_square.raceevent')),
            ],
        ),
    ]
