# Generated by Django 5.0.6 on 2024-05-23 15:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedraceevent',
            name='circuit_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Circuit layout'),
        ),
        migrations.AddField(
            model_name='detailedraceevent',
            name='circuit_info',
            field=models.TextField(default='placeholder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailedraceevent',
            name='circuit_name',
            field=models.CharField(default='placeholder'),
            preserve_default=False,
        ),
    ]
