# Generated by Django 5.0.6 on 2024-05-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_details', '0002_detailedraceevent_circuit_image_and_more'),
        ('town_square', '0004_alter_raceevent_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailedRaceEvent',
            new_name='RaceEventDetails',
        ),
    ]
