# Generated by Django 5.0.6 on 2024-05-25 09:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_details', '0005_alter_raceeventdetail_circuit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceeventdetail',
            name='circuit_image',
        ),
        migrations.RemoveField(
            model_name='raceeventdetail',
            name='circuit_info',
        ),
        migrations.AddField(
            model_name='raceeventdetail',
            name='circuit_length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='raceeventdetail',
            name='event_hero_image',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1716628663/default-hero.jpg', max_length=255, verbose_name='Hero image'),
        ),
        migrations.AddField(
            model_name='raceeventdetail',
            name='lap_record',
            field=models.CharField(default='x:xx.xxx', max_length=8, verbose_name='Lap record (x:xx.xxx)'),
        ),
        migrations.AddField(
            model_name='raceeventdetail',
            name='number_of_laps',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
