# Generated by Django 5.0.6 on 2024-05-25 09:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_details', '0006_remove_raceeventdetail_circuit_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceeventdetail',
            name='event_hero_image',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1716558951/checkered-flags.svg', max_length=255, verbose_name='Hero image'),
        ),
    ]
