# Generated by Django 5.0.6 on 2024-05-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_details', '0007_alter_raceeventdetail_event_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceeventdetail',
            name='circuit_length',
            field=models.FloatField(default=0),
        ),
    ]
