# Generated by Django 5.0.6 on 2024-06-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_details', '0009_raceeventcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raceeventcomment',
            options={'ordering': ['-created_on']},
        ),
    ]
